Refactored SAS URL API
LambdaTest/test-at-scale pull request #222
Opened 2022-07-13 20:30 UTC by saurabh-prakash

# Issue Link

Add GitHub issue links here.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-14 12:38 UTC, nevilm-lt requested changes

2022-07-14 13:06 UTC, saurabh-prakash commented on pkg/utils/utils.go
> +		"taskID":  os.Getenv("TASK_ID"),
incorporated. Thanks.

2022-07-14 13:06 UTC, saurabh-prakash commented on pkg/blocktestservice/setup.go
> +	query["taskID"] = tbs.cfg.TaskID
Looked at the flow. Not really.

2022-07-14 13:50 UTC, nevilm-lt approved these changes

2022-07-15 06:18 UTC, rishabh-arya95 approved these changes

2022-07-15 06:22 UTC, merged